### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by TheGreatWolf13** [TRSasasusu/TranslationForTheOutsider#1]
Hello, I'd like to contribute with the Brazilian Portuguese translation I made.

(It's a xml file, but as github doesn't allow for uploading xmls, I changed the extension to txt. Just changing it back should work fine.)

[portuguese_br.txt](https://github.com/TRSasasusu/TranslationForTheOutsider/files/11283442/portuguese_br.txt)

**Comment by TRSasasusu** [comment]
@MGSchultz-13 Thank you!! I will add it into next releases.

Now, I noticed Friend is Amigo in Brazilian Portuguese, so it is also colored as in Friend.

![スクリーンショット (2101)](https://user-images.githubusercontent.com/17728957/233365652-f8717806-b3c4-4af2-af89-353aa32235e5.png)

**Comment by TRSasasusu** [comment]
Your Brazilian Portuguese translation is released in [v0.3.0](https://github.com/TRSasasusu/TranslationForTheOutsider/releases/tag/v0.3.0)! (See [the mod page](https://outerwildsmods.com/mods/translationfortheoutsider/))

If you have any problems, please reopen this issue. Thank you!
