### ISSUE TITLE
Translation fixes 2 (ru)

### ISSUE THREAD

**Issue by Danielthas1988** [TRSasasusu/TranslationForTheOutsider#10]
Worked on grammar, punctuation, and corrected some logical errors

[russian.txt](https://github.com/TRSasasusu/TranslationForTheOutsider/files/11714800/russian.txt)

**Comment by TRSasasusu** [comment]
@Danielthas1988 Thank you!

Your translation fix is released in next version.

Now, I am working a major update which also fixes many bugs of The Outsider itself, and its release will be done in this week, I think.

**Comment by Danielthas1988** [comment]
Missed one little typo
Corrected it

[russian.txt](https://github.com/TRSasasusu/TranslationForTheOutsider/files/11770281/russian.txt)

**Comment by TRSasasusu** [comment]
Thank you, @Danielthas1988  
Your previous translation fix is released in [v1.0.0](https://github.com/TRSasasusu/TranslationForTheOutsider/releases/tag/v1.0.0).

And, your latest fix will be released in the next version.

**Comment by TRSasasusu** [comment]
It is released in [v1.0.1](https://github.com/TRSasasusu/TranslationForTheOutsider/releases/tag/v1.0.1).

Thank you!
