### ISSUE TITLE
Translation fixes 3 (ru)

### ISSUE THREAD

**Issue by Siroptas** [TRSasasusu/TranslationForTheOutsider#14]
Fixing a small logical error
[russian.txt](https://github.com/TRSasasusu/TranslationForTheOutsider/files/11893871/russian.txt)

**Comment by TRSasasusu** [comment]
Thank you, @Siroptas 
Your translation fix is released in [v1.1.1](https://github.com/TRSasasusu/TranslationForTheOutsider/releases/tag/v1.1.1)!
