### ISSUE TITLE
[Question]About Japanese-prohibited-characters

### ISSUE THREAD

**Issue by solitary-sails** [TRSasasusu/TranslationForTheOutsider#16]
I noticed that there is a file was named as  Japanese-prohibited-characters in the repository.  I'm a little curious if the characters in this file are the characters you found that can't be displayed properly in the game?

**Comment by TRSasasusu** [comment]
@solitary-sails Yes. Outer Wilds has some missing Japanese characters even though they are used in the base game like 'ぺ'.

I have a plan to make a Japanese font fix mod as in [the Chinese font fix mod](https://github.com/nice2cu1/OuterWildFixFont).

**Comment by solitary-sails** [comment]
I know that fix patch made by nice2cu1, we're in the same OICQ (A SNS like LINE) chat group. It's a little weird that "六" are already been used in Chinese translation of base game, and can be display well. I'm a little surprised that this character doesn't display correctly in the Japanese translation. So I suggest you investigate if there is some bug that let "六" can't display properly.

**Comment by solitary-sails** [comment]
BTW, since some characters in Japanese come from Chinese, the work of nice2cu1 is now able to fix part of the problems in the Japanese translation. I found out that "Nomaiの" in ship log about Dark Bramble was successfully restored back to "Nomaiの墓".

**Comment by solitary-sails** [comment]
BTW, since some characters are both exist in Japanese and Chinese, the work of nice2cu1 is now able to fix part of the problems in the Japanese translation. I found out that "Nomaiの" in ship log about Dark Bramble was successfully restored back to "Nomaiの墓".

**Comment by TRSasasusu** [comment]
ok, the plan is started:

![スクリーンショット (2312)](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/17728957/6ef835ee-5887-485d-97ab-2bfad4604af2)

![スクリーンショット (2315)](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/17728957/2344b75a-395f-44f1-a7ba-1baf80a94249)

I think the Chinese font asset and the Japanese font asset is completely separated, so "六" can be displayed in only Chinese.

**Comment by solitary-sails** [comment]
Thanks for answering. It is indeed possible that Chinese and Japanese use different assets. My question is over
