### ISSUE TITLE
Problem about highlight and colorize text

### ISSUE THREAD

**Issue by solitary-sails** [TRSasasusu/TranslationForTheOutsider#18]
I noticed that the current logic for highlighting and coloring is to replace the text in the Color Tab. But this can cause problems because the same word can mean different things. An example is shown in the screenshot.
"Friend" should be highlight when it was used as pronoun. But "friend" shown in the screenshot is a noun and should not be highlighted.
To solve this problem, I'm wondering if it's possible to remove the entire Color Tab and just write the tag about the highlight directly into the text. I don't know much about C#, will this cause bugs in your mod?
![friendInEnglish](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/52939914/09f53db6-2d44-4609-9374-4c21da0132b0)
![friendInChinese](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/52939914/e48183ac-7cb3-4dcb-bf33-e1247dac7b25)

**Comment by TRSasasusu** [comment]
I think it is fixed by [this commit](https://github.com/TRSasasusu/TranslationForTheOutsider/commit/01292598b54d55af392d66a76daf8517114dfa56). It will be released in the next release.

(Similar problem happened in Japanese. The ship is 船, and the Vessel is also 船. So, I introduce the ` syntax.)

**Comment by solitary-sails** [comment]
So all we need to do now is use `` to enclose the highlighted text?
BTW, I'm still curious if the method I mentioned above will work. Since my friend and I were recently considering retranslating The Outsider, we could write tags into the text while translating.So we could avoid this polysemy problem once and for all if this methos make sense.

**Comment by TRSasasusu** [comment]
Yes. Words enclosed by ` is distinguished from not enclosed words, and this symbol is removed in the final output. So, you can use this syntax to avoid the polysemy problems. Of course, explicitly using tags also works well.

Now, I checked some chinese texts, and they seem well, I think.

![スクリーンショット (2398)](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/17728957/fb788a0e-416c-4d93-ba8d-237d23069d82)

![スクリーンショット (2399)](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/17728957/deb4717f-2c66-47f5-b91a-f3377db8eba0)

![スクリーンショット (2400)](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/17728957/44533011-c754-4562-b6e6-6b6693f8fbd0)

![スクリーンショット (2401)](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/17728957/324b3230-f0a5-4e81-9829-d288d6e8150f)

![スクリーンショット (2403)](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/17728957/8072162c-3ec1-4996-bf39-4db6d3451af3)

**Comment by TRSasasusu** [comment]
It is released in [v1.1.3](https://github.com/TRSasasusu/TranslationForTheOutsider/releases/tag/v1.1.3). Thank you.
