### ISSUE TITLE
french please that we would be great 

### ISSUE THREAD

**Issue by Tristanos9** [TRSasasusu/TranslationForTheOutsider#2]
TranslationForTheOutsider/assets/<french>.xml

**Comment by TRSasasusu** [comment]
If you made a XML file for French, you can drag and drop here. I will add it into next releases!

**Comment by TRSasasusu** [comment]
But, Issue of GitHub cannot deal with XML file, so you have to change its extension `.xml` to `.txt`.

**Comment by TRSasasusu** [comment]
If you make `french.xml`, please reopen this issue!

Thank you.
