### ISSUE TITLE
Translation fixes 4 (ru)

### ISSUE THREAD

**Issue by Svetaleet** [TRSasasusu/TranslationForTheOutsider#23]
In the previous version of the translation, the missing elevator was mentioned in one of the dialogs (apparently a liberty of the first translator). Since the problem was fixed, the dialog was changed

[russian.txt](https://github.com/TRSasasusu/TranslationForTheOutsider/files/12715908/russian.txt)

**Comment by TRSasasusu** [comment]
@Svetaleet Thank you! It is released in [v1.3.0](https://github.com/TRSasasusu/TranslationForTheOutsider/releases/tag/v1.3.0).
