### ISSUE TITLE
Sun is still killing me even though I'm on the Stranger

### ISSUE THREAD

**Issue by Svetaleet** [TRSasasusu/TranslationForTheOutsider#29]
[Proof](https://youtu.be/c8Qq0s6HHbY).
As I understand it, the supernova is simulated by a blast wave from the fire in the Friend's house, as in the case of the second artifact. It happens regardless of which location you doze off in. Same thing with decreasing gravity.

**Comment by TRSasasusu** [comment]
the gravity effect is related to [`DreamGravityinator`](https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/blob/1e30bffea6ed17b7d801267707099e95ea2e4482/TheOutsider/OuterWildsHandling/GiantsDeepGravityEffects.cs#L141-L169).
the exploding is related to [`OnTriggerSupernova`](https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/blob/1e30bffea6ed17b7d801267707099e95ea2e4482/TheOutsider/OuterWildsHandling/OWPatches.cs#L500-L504) and [this](https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/blob/1e30bffea6ed17b7d801267707099e95ea2e4482/TheOutsider/OuterWildsHandling/SolarSystemHandler.cs#L90-L92).
so, i would fix them. thanks.

**Comment by TRSasasusu** [comment]
It is fixed when you on the stranger: 
![スクリーンショット (3405)](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/17728957/472cbc2a-d56f-4bf1-8b62-ea353e2ae544)

and it is released in [v1.3.4](https://github.com/TRSasasusu/TranslationForTheOutsider/releases/tag/v1.3.4).
