### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by Korol2038** [TRSasasusu/TranslationForTheOutsider#3]
Hi, I wanted to present my version of the translation I made.
The file extension was measured from .xml to .txt

[russian.txt](https://github.com/TRSasasusu/TranslationForTheOutsider/files/11476309/russian.txt)

**Comment by TRSasasusu** [comment]
@Korol2038 Thank you!

By adding [some lines](https://github.com/TRSasasusu/TranslationForTheOutsider/blob/b4b6bad7e8b7eebe2c0857309c6bdfba2476112b/TranslationForTheOutsider/assets/russian.xml#L4-L107), some words are colored as in English version now:
![スクリーンショット (2148)](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/17728957/ba66ff08-5ace-4fb1-be61-7fb1a8681872)

![スクリーンショット (2149)](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/17728957/0c264697-db36-4a97-87ac-fedd80ecdb8d)

These changes are released at soon.

**Comment by TRSasasusu** [comment]
Your translation is released in [v0.5.0](https://github.com/TRSasasusu/TranslationForTheOutsider/releases/tag/v0.5.0)! ([It is available in Outer Wilds Mod Manager.](https://outerwildsmods.com/mods/translationfortheoutsider/))

If you have any problems, please reopen this issue. Thank you!

**Comment by Korol2038** [comment]
Thank you very much!
I ran my eyes over it again and corrected a few minor grammatical errors.

[russian.txt](https://github.com/TRSasasusu/TranslationForTheOutsider/files/11485135/russian.txt)
