### ISSUE TITLE
Unrecognizable stones

### ISSUE THREAD

**Issue by Svetaleet** [TRSasasusu/TranslationForTheOutsider#30]
The signal of the stone in the Datura's house is unrecognizable (HOUSE SHARD?)
![Stone1](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/133753876/2d94ec70-993d-4548-93a9-4e127af5e165)

The rock in the observatory has no signal at all (OBSERVATORY SHARD?)
![Stone2](https://github.com/TRSasasusu/TranslationForTheOutsider/assets/133753876/fe1d4e33-638b-49a7-9335-608b51d0da36)

**Comment by TRSasasusu** [comment]
i know this issue and [its related code location](https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/blob/1e30bffea6ed17b7d801267707099e95ea2e4482/TheOutsider/OutsiderHandling/ObjectModificationSS.cs#L175-L185).
but, i don't know its name, and we cannot name it by not the author.
so, i cannot address this issue unless i got the correct name by the author someday.
if so, i would reopen this issue.

in contrast, i think the one in the northern observatory is sealed in the box.
this box could prevent the signal as the signal blocker does above the eye.

thanks.
