### ISSUE TITLE
Translation fixes (ru)

### ISSUE THREAD

**Issue by Svetaleet** [TRSasasusu/TranslationForTheOutsider#4]
Corrected a few minor grammatical errors I found yesterday while going through the mod

[russian.txt](https://github.com/TRSasasusu/TranslationForTheOutsider/files/11485731/russian.txt)

**Comment by Korol2038** [comment]
Thanks!

**Comment by TRSasasusu** [comment]
@Svetaleet Thank you!

It is released in [v0.5.1](https://github.com/TRSasasusu/TranslationForTheOutsider/releases/tag/v0.5.1)! (It is available in [Outer Wilds Mod Manager](https://outerwildsmods.com/mods/translationfortheoutsider/).)

If you have any problems, please reopen this issue.
